const _template = {
    "": {
        "Label": "",
        "Description": "",
        "Icon": "",
        "Rule_Value": "",
        "Multiply": 1,
        "Add": 0,
    },
}

export const Modifiers = {
    "Regeneration": {
        "Label": "Regeneration",
        "Description": "Increase health regeneration amount.",
        "Icon": "Regeneration",
        "Rule_Value": "Player.Bonus_Regeneration_Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "EnemySpawnAmount": {
        "Label": "More enemies",
        "Description": "Increase enemy spawn amount by 10%.",
        "Icon": "Enemy",
        "Rule_Value": "Player.Bonus_Enemy_Spawn_Amount_Multiplier",
        "Multiply": 1,
        "Add": 0.1,
    },
    "ExperienceBonus": {
        "Label": "More XP gain",
        "Description": "XP drops worth 10% more.",
        "Icon": "Experience",
        "Rule_Value": "Player.Bonus_Experience_Multiplier",
        "Multiply": 1,
        "Add": 0.1,
    },
    "HealingBonus": {
        "Label": "Healing bonus",
        "Description": "Health drops worth 10% more.",
        "Icon": "Heal",
        "Rule_Value": "Player.Bonus_Healing_Multiplier",
        "Multiply": 1,
        "Add": 0.1,
    },
    "HealAll": {
        "Label": "Heal to 100%",
        "Description": "Heal completely.",
        "Icon": "Heal",
        "Rule_Value": "Player.Health",
        "Rule_Max": "Player.Health_Max",
        "Multiply": 1,
        "Add": 1000000, // todo Infnity
    },
    "MaxHealth": {
        "Label": "Max health up",
        "Description": "By 10%, healing not included.",
        "Icon": "HealthMax",
        "Rule_Value": "Player.Health_Max",
        "Multiply": 1.1,
        "Add": 0,
    },
    "MovementSpeed": {
        "Label": "Speed up",
        "Description": "Increase movement speed slightly.",
        "Icon": "MoveSpeed",
        "Rule_Value": "Player.MovementSpeed",
        "Multiply": 1,
        "Add": 5,
    },
    "PickupDistance": {
        "Label": "Bigger pickup zone",
        "Description": "Attract drops from further.",
        "Icon": "PickupDistance",
        "Rule_Value": "Player.PickupDistance",
        "Multiply": 1,
        "Add": 10,
    },
    "WeaponDamage": {
        "Label": "All damage up",
        "Description": "Increase damage bonus by 5%.",
        "Icon": "WeaponDamage",
        "Rule_Value": "Player.Bonus_Weapon_Damage_Multiplier",
        "Multiply": 1,
        "Add": 0.05,
    },
    "WeaponDamage_Extra": {
        "Label": "All damage up a bit",
        "Description": "Increase damage bonus by 1%.",
        "Icon": "WeaponDamage",
        "Rule_Value": "Player.Bonus_Weapon_Damage_Multiplier",
        "Multiply": 1,
        "Add": 0.01,
    },
    "WeaponCooldown": {
        "Label": "Attack faster",
        "Description": "Reduce all weapon cooldowns by 5%.",
        "Icon": "WeaponCooldown",
        "Rule_Value": "Player.Bonus_Weapon_Cooldown_Multiplier",
        "Multiply": 1,
        "Add": -0.05,
    },
    "WeaponCooldown_Extra": {
        "Label": "Attack a bit faster",
        "Description": "Reduce all weapon cooldowns by 1%.",
        "Icon": "WeaponCooldown",
        "Rule_Value": "Player.Bonus_Weapon_Cooldown_Multiplier",
        "Multiply": 1,
        "Add": -0.01,
    },
    "WeaponSize": {
        "Label": "Bigger weapons",
        "Description": "Scale up all weapons.",
        "Icon": "WeaponSize",
        "Rule_Value": "Player.Bonus_Weapon_Size_Multiplier",
        "Multiply": 1,
        "Add": 0.10,
    },
    "WeaponAmount": {
        "Label": "+1 Weapon amount",
        "Description": "Increase all weapon amounts.",
        "Icon": "WeaponAmount",
        "Rule_Value": "Player.Bonus_Weapon_Amount_Extra",
        "Multiply": 1,
        "Add": 1,
    },
    "Axe_Amount": {
        "Weapon": "Axe", // to attack & reset cooldown
        "Label": "+1 Axe",
        "Description": "A trusty old throwing axe.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Axe_Damage": {
        "Weapon": "Axe",
        "Label": "Axe: +5 damage",
        "Description": "Deal bigger damage with your axe.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.Damage",
        "Multiply": 1,
        "Add": 5,
    },
    "Axe_Damage_Extra": {
        "Weapon": "Axe",
        "Label": "Axe: +2 damage",
        "Description": "Deal a bit bigger damage with your axe.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.Damage",
        "Multiply": 1,
        "Add": 2,
    },
    "Axe_PierceLimit": {
        "Weapon": "Axe",
        "Label": "Axe: +1 piercing",
        "Description": "Go through one more enemy.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.PierceLimit",
        "Multiply": 1,
        "Add": 1,
    },

    "Flame_Amount": {
        "Weapon": "Flame",
        "Label": "+1 Flame",
        "Description": "Cooks nearby enemies.",
        "Icon": "Flame",
        "Rule_Value": "Weapons.Flame.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Flame_Timeout": {
        "Weapon": "Flame",
        "Label": "Flame: fuel up",
        "Description": "Flames last longer.",
        "Icon": "Flame",
        "Rule_Value": "Weapons.Flame.Timeout",
        "Multiply": 1,
        "Add": 0.5,
    },

    "Chainsaw_Amount": {
        "Weapon": "Chainsaw",
        "Label": "+1 Chainsaw",
        "Description": "It orbits around you.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Chainsaw_Radius": {
        "Weapon": "Chainsaw",
        "Label": "Chainsaw: radius up",
        "Description": "Increase distance from player.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.OrbitRadius",
        "Multiply": 1,
        "Add": 10,
    },
    "Chainsaw_Size": {
        "Weapon": "Chainsaw",
        "Label": "Chainsaw: scale up",
        "Description": "Increase the size of your chainsaws.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.Scale",
        "Multiply": 1,
        "Add": 0.1,
    },
    "Chainsaw_Speed": {
        "Weapon": "Chainsaw",
        "Label": "Chainsaw: speed up",
        "Description": "Faster orbit speed for the chainsaws.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.OrbitSpeed",
        "Multiply": 1,
        "Add": 50,
    },

    "Spikes_Amount": {
        "Weapon": "Spikes",
        "Label": "+5 Spikes",
        "Description": "Spawns 5 more spike clusters.",
        "Icon": "Spikes",
        "Rule_Value": "Weapons.Spikes.Amount",
        "Multiply": 1,
        "Add": 5,
    },
    "Spikes_Area": {
        "Weapon": "Spikes",
        "Label": "Spikes: area up",
        "Description": "Spreads spikes on a bigger area",
        "Icon": "Spikes",
        "Rule_Value": "Weapons.Spikes.PositionRandom2",
        "Multiply": 1,
        "Add": 10,
    },
    "Spikes_Damage": {
        "Weapon": "Spikes",
        "Label": "Spikes: +5 damage",
        "Description": "Spikes do more damage.",
        "Icon": "Spikes",
        "Rule_Value": "Weapons.Spikes.Amount",
        "Multiply": 1,
        "Add": 5,
    },
    "Spikes_Damage_Extra": {
        "Weapon": "Spikes",
        "Label": "Spikes: +2 damage",
        "Description": "Spikes do bit more damage.",
        "Icon": "Spikes",
        "Rule_Value": "Weapons.Spikes.Amount",
        "Multiply": 1,
        "Add": 2,
    },
}