const _example = {
    "": {
        "Label": "Heal a bit",              // bigger text for the level up screen
        "Description": "Heal 100 points",   // smaller text for the level up screen
        "Icon": "Heal",                     // an animation name in the Icons object
        "Rule_Value": "Player.Health",      // specify which rule value to modify
        "Rule_Max": "Player.Health_Max",    // optionally specify the rule which holds the maximum allowed value
        //"Multiply": 1,                      // amount to multiply the specified rule value with (defaults to 1 when not specified or set to null)
        "Add": 100,                         // amount to add to the specified rule value
        "Weapon": "Axe"                     // optionally specify a weapon to immediately trigger its attack and restart its cooldown
    },
}

export const Modifiers = {
    "Regeneration": {
        "Label": "Regeneration",
        "Description": "Increase health regeneration amount.",
        "Icon": "Regeneration",
        "Rule_Value": "Player.Bonus_Regeneration_Amount",
        "Add": 1,
    },
    "EnemyMovementSpeed": {
        "Label": "Faster enemies",
        "Description": "Increase enemy movement speed by 10%.",
        "Icon": "Enemy",
        "Rule_Value": "Player.Bonus_Enemy_MovementSpeed_Multiplier",
        "Add": 0.1,
    },
    "EnemyMovementSpeedBig": {
        "Label": "Much faster enemies",
        "Description": "Increase enemy movement speed by 100%.",
        "Icon": "Enemy",
        "Rule_Value": "Player.Bonus_Enemy_MovementSpeed_Multiplier",
        "Add": 1,
    },
    "EnemySpawnAmount": {
        "Label": "More enemies",
        "Description": "Increase enemy spawn amount by 10%.",
        "Icon": "Enemy",
        "Rule_Value": "Player.Bonus_Enemy_Spawn_Amount_Multiplier",
        "Add": 0.1,
    },
    "ExperienceBonus": {
        "Label": "More XP gain",
        "Description": "XP drops worth 10% more.",
        "Icon": "Experience",
        "Rule_Value": "Player.Bonus_Experience_Multiplier",
        "Add": 0.1,
    },
    "HealingBonus": {
        "Label": "Healing bonus",
        "Description": "Increase healing efficiency by 10%.",
        "Icon": "Heal",
        "Rule_Value": "Player.Bonus_Healing_Multiplier",
        "Add": 0.1,
    },
    "Armor": {
        "Label": "Armor",
        "Description": "Reduce incoming damage by 5%.",
        "Icon": "Armor",
        "Rule_Value": "Player.Bonus_Incoming_Damage_Multiplier",
        "Add": -0.05,
    },
    "HealAll": {
        "Label": "Heal to 100%",
        "Description": "Heal completely.",
        "Icon": "Heal",
        "Rule_Value": "Player.Health",
        "Rule_Max": "Player.Health_Max",
        "Add": 1000000,
    },
    "MaxHealth": {
        "Label": "Max health to 110%",
        "Description": "Healing not included.",
        "Icon": "HealthMax",
        "Rule_Value": "Player.Health_Max",
        "Multiply": 1.1,
    },
    "MovementSpeed": {
        "Label": "Speed up",
        "Description": "Increase movement speed slightly.",
        "Icon": "MoveSpeed",
        "Rule_Value": "Player.MovementSpeed",
        "Add": 5,
    },
    "PickupDistance": {
        "Label": "Bigger pickup zone",
        "Description": "Attract drops from further.",
        "Icon": "PickupDistance",
        "Rule_Value": "Player.PickupDistance",
        "Add": 10,
    },
    "LevelUpFreezeTime": {
        "Label": "Freeze time",
        "Description": "Longer freeze time after level up.",
        "Icon": "Ice",
        "Rule_Value": "Player.LevelUpFreezeTime",
        "Add": 0.2,
    },
    "WeaponDamage": {
        "Label": "All damage up",
        "Description": "Increase damage bonus by 5%.",
        "Icon": "WeaponDamage",
        "Rule_Value": "Player.Bonus_Weapon_Damage_Multiplier",
        "Add": 0.05,
    },
    "WeaponDamage_Extra": {
        "Label": "All damage up a bit",
        "Description": "Increase damage bonus by 1%.",
        "Icon": "WeaponDamage",
        "Rule_Value": "Player.Bonus_Weapon_Damage_Multiplier",
        "Add": 0.01,
    },
    "WeaponCooldown": {
        "Label": "Attack faster",
        "Description": "Reduce all weapon cooldowns by 5%.",
        "Icon": "WeaponCooldown",
        "Rule_Value": "Player.Bonus_Weapon_Cooldown_Multiplier",
        "Add": -0.05,
    },
    "WeaponCooldown_Extra": {
        "Label": "Attack a bit faster",
        "Description": "Reduce all weapon cooldowns by 1%.",
        "Icon": "WeaponCooldown",
        "Rule_Value": "Player.Bonus_Weapon_Cooldown_Multiplier",
        "Add": -0.01,
    },
    "WeaponSize": {
        "Label": "Bigger weapons",
        "Description": "Scale up all weapons.",
        "Icon": "WeaponSize",
        "Rule_Value": "Player.Bonus_Weapon_Size_Multiplier",
        "Add": 0.10,
    },
    "WeaponAmount": {
        "Label": "+1 Weapon amount",
        "Description": "Increase all weapon amounts.",
        "Icon": "WeaponAmount",
        "Rule_Value": "Player.Bonus_Weapon_Amount",
        "Add": 1,
    },
    "Axe_Amount": {
        "Weapon": "Axe",
        "Label": "+1 Axe",
        "Description": "A trusty old throwing axe.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.Amount",
        "Add": 1,
    },
    "Axe_Damage": {
        "Weapon": "Axe",
        "Label": "Axe: +5 damage",
        "Description": "Deal bigger damage with your axe.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.Damage",
        "Add": 5,
    },
    "Axe_Damage_Extra": {
        "Weapon": "Axe",
        "Label": "Axe: +2 damage",
        "Description": "Deal a bit bigger damage with your axe.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.Damage",
        "Add": 2,
    },
    "Axe_PierceLimit": {
        "Weapon": "Axe",
        "Label": "Axe: +1 piercing",
        "Description": "Go through one more enemy.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.PierceLimit",
        "Add": 1,
    },

    "Flame_Amount": {
        "Weapon": "Flame",
        "Label": "+1 Flame",
        "Description": "Cooks nearby enemies.",
        "Icon": "Flame",
        "Rule_Value": "Weapons.Flame.Amount",
        "Add": 1,
    },
    "Flame_Duration": {
        "Weapon": "Flame",
        "Label": "Flame: fuel up",
        "Description": "Flames last longer.",
        "Icon": "Flame",
        "Rule_Value": "Weapons.Flame.Duration",
        "Add": 0.5,
    },

    "Chainsaw_Amount": {
        "Weapon": "Chainsaw",
        "Label": "+1 Chainsaw",
        "Description": "It orbits around you.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.Amount",
        "Add": 1,
    },
    "Chainsaw_Radius": {
        "Weapon": "Chainsaw",
        "Label": "Chainsaw: radius up",
        "Description": "Increase distance from player.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.OrbitRadius",
        "Add": 10,
    },
    "Chainsaw_Size": {
        "Weapon": "Chainsaw",
        "Label": "Chainsaw: scale up",
        "Description": "Increase the size of your chainsaws.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.Scale",
        "Add": 0.1,
    },
    "Chainsaw_Speed": {
        "Weapon": "Chainsaw",
        "Label": "Chainsaw: speed up",
        "Description": "Faster orbit speed for the chainsaws.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.OrbitSpeed",
        "Add": 50,
    },

    "Spikes_Amount": {
        "Weapon": "Spikes",
        "Label": "+1 Spikes",
        "Description": "Spawns spike clusters.",
        "Icon": "Spikes",
        "Rule_Value": "Weapons.Spikes.Amount",
        "Add": 5,
    },
    "Spikes_Area": {
        "Weapon": "Spikes",
        "Label": "Spikes: area up",
        "Description": "Spreads spikes on a bigger area.",
        "Icon": "Spikes",
        "Rule_Value": "Weapons.Spikes.PositionRandom2",
        "Add": 10,
    },
    "Spikes_Damage": {
        "Weapon": "Spikes",
        "Label": "Spikes: +5 damage",
        "Description": "Spikes do more damage.",
        "Icon": "Spikes",
        "Rule_Value": "Weapons.Spikes.Amount",
        "Add": 5,
    },
    "Spikes_Damage_Extra": {
        "Weapon": "Spikes",
        "Label": "Spikes: +2 damage",
        "Description": "Spikes do a bit more damage.",
        "Icon": "Spikes",
        "Rule_Value": "Weapons.Spikes.Amount",
        "Add": 2,
    },

    "Ice_Amount": {
        "Weapon": "Ice",
        "Label": "+1 Ice Wheel",
        "Description": "Spawns a rotating ice wheel nearby.",
        "Icon": "Ice",
        "Rule_Value": "Weapons.Ice.Amount",
        "Add": 8,
    },
    "Ice_Duration": {
        "Weapon": "Ice",
        "Label": "Ice wheel: duration up",
        "Description": "Ice wheel lasts 0.5s longer.",
        "Icon": "Ice",
        "Rule_Value": "Weapons.Ice.Duration",
        "Add": 0.5,
    },
    "Ice_FreezeTime": {
        "Weapon": "Ice",
        "Label": "Ice wheel: freeze longer",
        "Description": "Ice wheel freezes enemies 0.5s longer.",
        "Icon": "Ice",
        "Rule_Value": "Weapons.Ice.FreezeTime",
        "Add": 0.5,
    },

    "Sword_Amount": {
        "Weapon": "Sword",
        "Label": "+1 Sword",
        "Description": "Slash!",
        "Icon": "Sword",
        "Rule_Value": "Weapons.Sword.Amount",
        "Add": 1,
    },
    "Sword_Damage": {
        "Weapon": "Sword",
        "Label": "Sword: +5 damage",
        "Description": "Sword does more damage.",
        "Icon": "Sword",
        "Rule_Value": "Weapons.Sword.Damage",
        "Add": 5,
    },
    "Sword_Size": {
        "Weapon": "Sword",
        "Label": "Sword: scale up",
        "Description": "Increase the size of your sword.",
        "Icon": "Sword",
        "Rule_Value": "Weapons.Sword.Scale",
        "Multiply": 1.15,
    },
}