export const Modifiers = {
    "EnemySpawnCooldown": {
        "Label": "More enemies",
        "Description": "Reduce enemy spawn cooldown by 5%.",
        "Icon": "Enemy",
        "Rule_Value": "Player.Bonus_Enemy_Spawn_Cooldown_Multiplier",
        "Multiply": 1,
        "Add": -0.05,
    },
    "ExperienceBonus": {
        "Label": "More XP gain",
        "Description": "XP drops worth 10% more.",
        "Icon": "Experience",
        "Rule_Value": "Player.Bonus_Experience_Multiplier",
        "Multiply": 1,
        "Add": 0.1
    },
    "HealingBonus": {
        "Label": "Healing bonus",
        "Description": "Health drops worth 10% more.",
        "Icon": "HeartBlack",
        "Rule_Value": "Player.Bonus_Healing_Multiplier",
        "Multiply": 1,
        "Add": 0.1
    },
    "HealMax": {
        "Label": "Heal to 100%",
        "Description": "Heal completely.",
        "Icon": "Heal",
        "Rule_Value": "Player.Health",
        "Rule_Max": "Player.Health_Max",
        "Multiply": 1,
        "Add": 100000
    },
    "MaxHealth": {
        "Label": "Max health up",
        "Description": "By 10%, healing not included.",
        "Icon": "HealthMax",
        "Rule_Value": "Player.Health_Max",
        "Multiply": 1.1,
        "Add": 0
    },
    "MovementSpeed": {
        "Label": "Speed up",
        "Description": "Increase movement speed slightly.",
        "Icon": "MoveSpeed",
        "Rule_Value": "Player.MovementSpeed",
        "Multiply": 1,
        "Add": 5
    },
    "PickupDistance": {
        "Label": "Bigger pickup zone",
        "Description": "Attract drops from further.",
        "Icon": "PickupDistance",
        "Rule_Value": "Player.PickupDistance",
        "Multiply": 1,
        "Add": 10
    },
    "WeaponDamage": {
        "Label": "Damage up",
        "Description": "Increase damage bonus by 5%.",
        "Icon": "WeaponDamage",
        "Rule_Value": "Player.Bonus_Weapon_Damage_Multiplier",
        "Multiply": 1,
        "Add": 0.05,
    },
    "WeaponCooldown": {
        "Label": "Attack faster",
        "Description": "Reduce all weapon cooldowns by 5%.",
        "Icon": "WeaponCooldown",
        "Rule_Value": "Player.Bonus_Weapon_Cooldown_Multiplier",
        "Multiply": 1,
        "Add": -0.05,
    },
    "WeaponSize": {
        "Label": "Bigger weapons",
        "Description": "Scale up all weapons.",
        "Icon": "WeaponSize",
        "Rule_Value": "Player.Bonus_Weapon_Size_Multiplier",
        "Multiply": 1,
        "Add": 0.10,
    },
    "WeaponAmount": {
        "Label": "+1 Weapon amount",
        "Description": "Increase all weapon amounts.",
        "Icon": "WeaponAmount",
        "Rule_Value": "Player.Bonus_Weapon_Amount_Extra",
        "Multiply": 1,
        "Add": 1,
    },
    "Axe_Amount": {
        "Label": "+1 Axe",
        "Weapon": "Axe",
        "Description": "A trusty old throwing axe.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Axe_Damage": {
        "Weapon": "Axe",
        "WeaponRequirement": "Axe",
        "Label": "Axe: damage up",
        "Description": "Deal bigger damage with your axe.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.Damage",
        "Multiply": 1,
        "Add": 5,
    },
    "Axe_PierceLimit": {
        "Weapon": "Axe",
        "WeaponRequirement": "Axe",
        "Label": "Axe: +1 piercing",
        "Description": "Go through one more enemy.",
        "Icon": "Axe",
        "Rule_Value": "Weapons.Axe.PierceLimit",
        "Multiply": 1,
        "Add": 1,
    },
    "Flame": {
        "Weapon": "Flame",
        "Label": "+1 Flame",
        "Description": "Cooks nearby enemies.",
        "Icon": "Flame",
        "Rule_Value": "Weapons.Flame.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Flame_Timeout": {
        "Weapon": "Flame",
        "WeaponRequirement": "Flame",
        "Label": "Flame: fuel up",
        "Description": "Flames last longer.",
        "Icon": "Flame",
        "Rule_Value": "Weapons.Flame.Timeout",
        "Multiply": 1,
        "Add": 0.2,
    },
    "Chainsaw": {
        "Weapon": "Chainsaw",
        "Label": "+1 Chainsaw",
        "Description": "It orbits around you.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Chainsaw_Radius": {
        "Weapon": "Chainsaw",
        "WeaponRequirement": "Chainsaw",
        "Label": "Chainsaw: radius up",
        "Description": "Increase distance from player.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.OrbitRadius",
        "Multiply": 1,
        "Add": 10,
    },
    "Chainsaw_Size": {
        "Weapon": "Chainsaw",
        "WeaponRequirement": "Chainsaw",
        "Label": "Chainsaw: scale up",
        "Description": "Increase the size of your chainsaws.",
        "Icon": "Chainsaw",
        "Rule_Value": "Weapons.Chainsaw.Scale",
        "Multiply": 1,
        "Add": 0.1,
    },
    "Spikes": {
        "Weapon": "Spikes",
        "Label": "+1 Spikes",
        "Description": "Spawns spikes on the ground.",
        "Icon": "Spikes",
        "Rule_Value": "Weapons.Spikes.Amount",
        "Multiply": 1,
        "Add": 5,
    },
    "Spikes_Area": {
        "Weapon": "Spikes",
        "WeaponRequirement": "Spikes",
        "Label": "Spikes: area up",
        "Description": "Spreads spikes on a bigger area",
        "Icon": "Spikes",
        "Rule_Value": "Weapons.Spikes.PositionRandom2",
        "Multiply": 1,
        "Add": 10,
    },
}