export const Upgrades = {
    "EnemySpawnCooldown": {
        "Label": "More enemies",
        "Description": "Reduce enemy spawn cooldown by 5%.",
        "Icon": "Enemy",
        "Rule_Value": "Player.Bonus_Enemy_Spawn_Cooldown_Multiplier",
        "Multiply": 1,
        "Add": -0.05,
    },
    "ExperienceBonus": {
        "Label": "More XP gain",
        "Description": "XP drops worth 10% more.",
        "Icon": "Experience",
        "Rule_Value": "Player.Bonus_Experience_Multiplier",
        "Multiply": 1,
        "Add": 0.1
    },
    "Heal1": {
        "Label": "Minor healing",
        "Description": "Heal 150 points.",
        "Icon": "Heal1",
        "Rule_Value": "Player.Health",
        "Rule_Max": "Player.Health_Max",
        "Multiply": 1,
        "Add": 150
    },
    "Heal2": {
        "Label": "Major healing",
        "Description": "Heal 500 points.",
        "Icon": "Heal2",
        "Rule_Value": "Player.Health",
        "Rule_Max": "Player.Health_Max",
        "Multiply": 1,
        "Add": 500
    },
    "ItemSpawnCooldown": {
        "Label": "More items",
        "Description": "Reduce item spawn cooldown by 5%.",
        "Icon": "Item",
        "Rule_Value": "Player.Bonus_Item_Spawn_Cooldown_Multiplier",
        "Multiply": 1,
        "Add": -0.05,
    },
    "MaxHealth": {
        "Label": "Max health up",
        "Description": "By 10%, healing not included.",
        "Icon": "HeartBlack",
        "Rule_Value": "Player.Health_Max",
        "Multiply": 1.1,
        "Add": 0
    },
    "MovementSpeed": {
        "Label": "Speed up",
        "Description": "Increase movement speed slightly.",
        "Icon": "GoldArrowRight",
        "Rule_Value": "Player.MovementSpeed",
        "Multiply": 1,
        "Add": 5
    },
    "PickupDistance": {
        "Label": "Bigger pickup zone",
        "Description": "Attract drops from further.",
        "Icon": "Experience",
        "Rule_Value": "Player.PickupDistance",
        "Multiply": 1,
        "Add": 10
    },
    "WeaponDamage": {
        "Label": "Damage up",
        "Description": "Increase damage bonus by 5%.",
        "Icon": "WeaponDamage",
        "Rule_Value": "Player.Bonus_Weapon_Damage_Multiplier",
        "Multiply": 1,
        "Add": 0.05,
    },
    "WeaponCooldown": {
        "Label": "Attack faster",
        "Description": "Increase cooldown bonus by 5%.",
        "Icon": "WeaponCooldown",
        "Rule_Value": "Player.Bonus_Weapon_Cooldown_Multiplier",
        "Multiply": 1,
        "Add": -0.05,
    },
    "WeaponSize": {
        "Label": "Bigger weapons",
        "Description": "Scale up all weapons.",
        "Icon": "WeaponSize",
        "Rule_Value": "Player.Bonus_Weapon_Size_Multiplier",
        "Multiply": 1,
        "Add": 0.10,
    },
    "WeaponAmount": {
        "Label": "+1 Weapon amount",
        "Description": "Increase all weapon amounts.",
        "Icon": "WeaponAmount",
        "Rule_Value": "Player.Bonus_Weapon_Amount_Extra",
        "Multiply": 1,
        "Add": 1,
    },
    "Sword": {
        "Label": "+1 Sword",
        "Description": "A sword that you throw. A Thrword.",
        "Icon": "Sword",
        "Rule_Value": "Weapons.Sword.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Flame": {
        "Label": "+1 Flame",
        "Description": "Cooks nearby enemies.",
        "Icon": "Flame",
        "Rule_Value": "Weapons.Flame.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Revolver": {
        "Label": "+1 Revolver",
        "Description": "It orbits around you.",
        "Icon": "Revolver",
        "Rule_Value": "Weapons.Revolver.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Myst": {
        "Label": "Myst / density",
        "Description": "Creates a damaging zone.",
        "Icon": "Myst",
        "Rule_Value": "Weapons.Myst.Amount",
        "Multiply": 1,
        "Add": 5,
    },
    "Myst_Area": {
        "WeaponRequirement": "Myst",
        "Label": "Myst: bigger area",
        "Description": "Spreads Myst on a bigger area",
        "Icon": "Myst",
        "Rule_Value": "Weapons.Myst.PositionRandom2",
        "Multiply": 1,
        "Add": 10,
    },
}