export const Upgrades = {
    "EnemySpawnCooldown": {
        "Label": "More enemies",
        "Description": "Reduce enemy spawn cooldown by 5%.",
        "Icon": "Enemy",
        "Rule_Value": "Player.Bonus_Enemy_Spawn_Cooldown_Multiplier",
        "Multiply": 1,
        "Add": -0.05,
    },
    "ExperienceBonus": {
        "Label": "More XP gain",
        "Description": "XP drops worth 10% more.",
        "Icon": "Experience",
        "Rule_Value": "Player.Bonus_Experience_Multiplier",
        "Multiply": 1,
        "Add": 0.1
    },
    "HealingBonus": {
        "Label": "Healing bonus",
        "Description": "Health drops worth 10% more.",
        "Icon": "HeartBlack",
        "Rule_Value": "Player.Bonus_Healing_Multiplier",
        "Multiply": 1,
        "Add": 0.1
    },
    "HealMax": {
        "Label": "Heal to 100%",
        "Description": "Heal completely.",
        "Icon": "Heal",
        "Rule_Value": "Player.Health",
        "Rule_Max": "Player.Health_Max",
        "Multiply": 1,
        "Add": 100000
    },
    "ItemSpawnCooldown": {
        "Label": "More items",
        "Description": "Reduce item spawn cooldown by 5%.",
        "Icon": "Item",
        "Rule_Value": "Player.Bonus_Item_Spawn_Cooldown_Multiplier",
        "Multiply": 1,
        "Add": -0.05,
    },
    "MaxHealth": {
        "Label": "Max health up",
        "Description": "By 10%, healing not included.",
        "Icon": "HealthMax",
        "Rule_Value": "Player.Health_Max",
        "Multiply": 1.1,
        "Add": 0
    },
    "MovementSpeed": {
        "Label": "Speed up",
        "Description": "Increase movement speed slightly.",
        "Icon": "GoldArrowRight",
        "Rule_Value": "Player.MovementSpeed",
        "Multiply": 1,
        "Add": 5
    },
    "PickupDistance": {
        "Label": "Bigger pickup zone",
        "Description": "Attract drops from further.",
        "Icon": "Experience",
        "Rule_Value": "Player.PickupDistance",
        "Multiply": 1,
        "Add": 10
    },
    "WeaponDamage": {
        "Label": "Damage up",
        "Description": "Increase damage bonus by 5%.",
        "Icon": "WeaponDamage",
        "Rule_Value": "Player.Bonus_Weapon_Damage_Multiplier",
        "Multiply": 1,
        "Add": 0.05,
    },
    "WeaponCooldown": {
        "Label": "Attack faster",
        "Description": "Increase cooldown bonus by 5%.",
        "Icon": "WeaponCooldown",
        "Rule_Value": "Player.Bonus_Weapon_Cooldown_Multiplier",
        "Multiply": 1,
        "Add": -0.05,
    },
    "WeaponSize": {
        "Label": "Bigger weapons",
        "Description": "Scale up all weapons.",
        "Icon": "WeaponSize",
        "Rule_Value": "Player.Bonus_Weapon_Size_Multiplier",
        "Multiply": 1,
        "Add": 0.10,
    },
    "WeaponAmount": {
        "Label": "+1 Weapon amount",
        "Description": "Increase all weapon amounts.",
        "Icon": "WeaponAmount",
        "Rule_Value": "Player.Bonus_Weapon_Amount_Extra",
        "Multiply": 1,
        "Add": 1,
    },
    "Sword": {
        "Label": "+1 Sword",
        "Description": "A sword that you throw. A Thrword.",
        "Icon": "Sword",
        "Rule_Value": "Weapons.Sword.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Sword_Damage": {
        "WeaponRequirement": "Sword",
        "Label": "Sword: damage up",
        "Description": "Deal bigger damage with your sword.",
        "Icon": "Sword",
        "Rule_Value": "Weapons.Sword.Damage",
        "Multiply": 1,
        "Add": 5,
    },
    "Sword_PierceLimit": {
        "WeaponRequirement": "Sword",
        "Label": "Sword: +1 piercing",
        "Description": "Go through one more enemy.",
        "Icon": "Sword",
        "Rule_Value": "Weapons.Sword.PierceLimit",
        "Multiply": 1,
        "Add": 1,
    },
    "Flame": {
        "Label": "+1 Flame",
        "Description": "Cooks nearby enemies.",
        "Icon": "Flame",
        "Rule_Value": "Weapons.Flame.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Flame_Timeout": {
        "WeaponRequirement": "Flame",
        "Label": "Flame: fuel up",
        "Description": "Flames last longer.",
        "Icon": "Flame",
        "Rule_Value": "Weapons.Flame.Timeout",
        "Multiply": 1,
        "Add": 0.2,
    },
    "Revolver": {
        "Label": "+1 Revolver",
        "Description": "It orbits around you.",
        "Icon": "Revolver",
        "Rule_Value": "Weapons.Revolver.Amount",
        "Multiply": 1,
        "Add": 1,
    },
    "Revolver_Radius": {
        "WeaponRequirement": "Revolver",
        "Label": "Revolver: radius up",
        "Description": "Increase distance from player.",
        "Icon": "Revolver",
        "Rule_Value": "Weapons.Revolver.OrbitRadius",
        "Multiply": 1,
        "Add": 10,
    },
    "Revolver_Size": {
        "WeaponRequirement": "Revolver",
        "Label": "Revolver: scale up",
        "Description": "Increase the size of your revolvers.",
        "Icon": "Revolver",
        "Rule_Value": "Weapons.Revolver.Scale",
        "Multiply": 1,
        "Add": 0.1,
    },
    "Myst": {
        "Label": "+1 Myst",
        "Description": "Spawns damaging zones.",
        "Icon": "Myst",
        "Rule_Value": "Weapons.Myst.Amount",
        "Multiply": 1,
        "Add": 5,
    },
    "Myst_Area": {
        "WeaponRequirement": "Myst",
        "Label": "Myst: area up",
        "Description": "Spreads Myst on a bigger area",
        "Icon": "Myst",
        "Rule_Value": "Weapons.Myst.PositionRandom2",
        "Multiply": 1,
        "Add": 10,
    },
}
// todo limit how many time an upgrade shows up