export const Waves = [ // todo_maybe remove spawn cooldown and just use a fixed 1 sec spawn cooldown (like in VS)?
    {
        "Name": "Welcome!",
        "EnemySpawnCycles": 1,
        "EnemySpawnCooldown": 3,
        "EnemySpawnPerCycle": 0,
        "EnemySpawnPool": [],
        "EnemySpawnFixed": {},
        "ItemSpawnPool": [],
    },
    {
        "Name": "And now: Slimes & Rats!",
        "EnemySpawnCycles": 20,
        "EnemySpawnCooldown": 3,
        "EnemySpawnAmountPerWave": 200,
        "EnemySpawnPool": [[40, "Slime"], [20, "Rat"]],
        "EnemySpawnFixed": {},
        "ItemSpawnPool": [[1, "Axe"], [1, "Flame"]],
    },
    {
        "Name": "Now some Crabs & Snakes. And a Tentacle.",
        "EnemySpawnCycles": 20,
        "EnemySpawnCooldown": 3,
        "EnemySpawnAmountPerWave": 60,
        "EnemySpawnPool": [[5, "Crab"], [5, "Snake"]],
        "EnemySpawnFixed": { "Tentacle": 1 },
        "ItemSpawnPool": [[1, "Chainsaw"], [1, "Spikes"]],
    },
    {
        "Name": "Need some healin'?",
        "EnemySpawnCycles": 10,
        "EnemySpawnCooldown": 3,
        "EnemySpawnAmountPerWave": 0,
        "EnemySpawnPool": [],
        "EnemySpawnFixed": { "HealingCrate": 3 },
        "ItemSpawnPool": [],
    },
    {
        "Name": "Get ready..",
        "EnemySpawnCycles": 120,
        "EnemySpawnCooldown": 1,
        "EnemySpawnAmountPerWave": 400,
        "EnemySpawnPool": [[40, "Slime"], [20, "Rat"], [5, "Crab"], [5, "Snake"], [3, "Werewolf"], [2, "Ent"]],
        "EnemySpawnFixed": {},
        "ItemSpawnPool": [[1, "Axe"], [1, "Flame"], [1, "Chainsaw"], [1, "Spikes"]],
    },
    {
        "Name": "Incoming healing crates...",
        "EnemySpawnCycles": 10,
        "EnemySpawnCooldown": 3,
        "EnemySpawnAmountPerWave": 0,
        "EnemySpawnPool": [],
        "EnemySpawnFixed": { "HealingCrate": 5 },
        "ItemSpawnPool": [],
    },
    {
        "Name": "And now... everything.",
        "EnemySpawnCycles": 1,
        "EnemySpawnCooldown": 3,
        "EnemySpawnPerCycle": 0,
        "EnemySpawnPool": [],
        "EnemySpawnFixed": {},
        "ItemSpawnPool": [],
    },
    {
        "Name": "",
        "EnemySpawnCycles": 180,
        "EnemySpawnCooldown": 1,
        "EnemySpawnAmountPerWave": 600,
        "EnemySpawnPool": [[1, "HealingCrate"], [40, "Slime"], [20, "Rat"], [5, "Crab"], [5, "Snake"], [3, "Werewolf"], [2, "Ent"], [2, "Tentacle"], [2, "Dwarf"], [2, "Golem"], [2, "Ogre"], [1, "Cultist"], [1, "Beholder"]],
        "EnemySpawnFixed": {},
        "ItemSpawnPool": [[1, "Axe"], [1, "Flame"], [1, "Chainsaw"], [1, "Spikes"]],
    },
]