export const Waves = [
    {
        "Name": "Welcome!",
        "EnemyAmount": 0,
        "Time": 3,
        //"EnemySpawnPool": [],
        "EnemySpawnFixed": { "MagnetCrate": 1 },
        //"ItemSpawnPool": [],
    },
    {
        "Name": "And now: Slimes & Rats!",
        "EnemyAmount": 200,
        "Time": 60,
        "EnemySpawnPool": [[2, "Slime"], [1, "Rat"]],
        //"EnemySpawnFixed": {},
        "ItemSpawnPool": [[1, "Axe_Amount"], [1, "Flame_Amount"]],
    },
    {
        "Name": "Now some Crabs & Snakes. And a Tentacle.",
        "EnemyAmount": 60,
        "Time": 60,
        "EnemySpawnPool": [[1, "Crab"], [1, "Snake"]],
        "EnemySpawnFixed": { "Tentacle": 1 },
        "ItemSpawnPool": [[1, "Chainsaw_Amount"], [1, "Spikes_Amount"]],
    },
    {
        "Name": "Need some healin'?",
        "EnemyAmount": 0,
        "Time": 3,
        //"EnemySpawnPool": [],
        "EnemySpawnFixed": { "HealingCrate": 3 },
        //"ItemSpawnPool": [],
    },
    {
        "Name": "Get ready..",
        "EnemyAmount": 400,
        "Time": 120,
        "EnemySpawnPool": [[0.5, "MagnetCrate"], [40, "Slime"], [20, "Rat"], [5, "Crab"], [5, "Snake"], [3, "Werewolf"], [2, "Ent"]],
        //"EnemySpawnFixed": {},
        "ItemSpawnPool": [[1, "Axe_Amount"], [1, "Flame_Amount"], [1, "Chainsaw_Amount"], [1, "Spikes_Amount"]],
    },
    {
        "Name": "Incoming healing crates...",
        "Time": 3,
        //"EnemySpawnPool": [],
        "EnemySpawnFixed": { "HealingCrate": 5 },
        //"ItemSpawnPool": [],
    },
    {
        "Name": "And now... everything.",
        "Time": 3,/*
        "EnemySpawnPool": [],
        "EnemySpawnFixed": {},
        "ItemSpawnPool": [],*/
    },
    {
        //"Name": "",
        "EnemyAmount": 200,
        "Time": 60,
        "EnemySpawnPool": [[0.5, "MagnetCrate"], [1, "HealingCrate"], [40, "Slime"], [20, "Rat"], [5, "Crab"], [5, "Snake"], [3, "Werewolf"], [2, "Ent"], [2, "Tentacle"], [2, "Dwarf"], [2, "Golem"], [2, "Ogre"], [1, "Cultist"], [1, "Beholder"]],
        "EnemySpawnFixed": {},
        "ItemSpawnPool": [[1, "Axe_Amount"], [1, "Flame_Amount"], [1, "Chainsaw_Amount"], [1, "Spikes_Amount"]],
    },
    {
        //"Name": "",
        "EnemyAmount": 400,
        "Time": 60,
        "EnemySpawnPool": [[0.5, "MagnetCrate"], [1, "HealingCrate"], [40, "Slime"], [20, "Rat"], [5, "Crab"], [5, "Snake"], [3, "Werewolf"], [2, "Ent"], [2, "Tentacle"], [2, "Dwarf"], [2, "Golem"], [2, "Ogre"], [1, "Cultist"], [1, "Beholder"]],
        "EnemySpawnFixed": {},
        "ItemSpawnPool": [[1, "Axe_Amount"], [1, "Flame_Amount"], [1, "Chainsaw_Amount"], [1, "Spikes_Amount"]],
    },
    {
        //"Name": "",
        "EnemyAmount": 600,
        "Time": 60,
        "EnemySpawnPool": [[1, "HealingCrate"], [40, "Slime"], [20, "Rat"], [5, "Crab"], [5, "Snake"], [3, "Werewolf"], [2, "Ent"], [2, "Tentacle"], [2, "Dwarf"], [2, "Golem"], [2, "Ogre"], [1, "Cultist"], [1, "Beholder"]],
        //"EnemySpawnFixed": {},
        //"ItemSpawnPool": [],
    },
    {
        //"Name": "",
        //"EnemyAmount": 0,
        "Time": 30,
        //"EnemySpawnPool": [],
        "EnemySpawnFixed": { "MagnetCrate": 1 },
        //"ItemSpawnPool": [],
    },

]