export const Weapons = {
    "Sword": {
        "Cooldown": 1,
        "Amount": 1,
        "Damage": 15,
        "PierceLimit": 5,
        "Scale": 1,
        "Timeout": 4,
        "MovementSpeed": 85,
        "Timer": 1,
        "Pin": 0,
        "OrbitRadius": 0,
        "OrbitSpeed": 0,
    },
    "Flame": {
        "Cooldown": 3,
        "Amount": 2,
        "Damage": 25,
        "PierceLimit": 1000,
        "Scale": 1,
        "Timeout": 0.5,
        "MovementSpeed": 10,
        "Timer": 1,
        "Pin": 1,
        "OrbitRadius": 0,
        "OrbitSpeed": 0,
    },
    "Revolver": {
        "Cooldown": 5,
        "Amount": 3,
        "Damage": 20,
        "PierceLimit": 1000,
        "Scale": 1,
        "Timeout": 4,
        "MovementSpeed": 20,
        "Timer": 1,
        "Pin": 1,
        "OrbitRadius": 40,
        "OrbitSpeed": 150,
    }
}