export const Weapons = {
    "_Template": {
        "BlockMovement": 1,
        "Cooldown": 2,
        "Amount": 0,
        "Damage": 0,
        "PierceLimit": 1,
        "Scale": 1,
        "Timeout": 4,
        "MovementSpeed": 0,
        "MovementAcceleration": 0,
        "Pin": 0,
        "OrbitRadius": 0,
        "OrbitSpeed": 0,
        "PositionRandom1": 0,
        "PositionRandom2": 0,
    },
    "Sword": {
        "BlockMovement": 1,
        "Cooldown": 1.5,
        "Amount": 1,
        "Damage": 15,
        "PierceLimit": 2,
        "Scale": 1,
        "Timeout": 4,
        "MovementSpeed": 85,
    },
    "Flame": {
        "BlockMovement": 1,
        "Cooldown": 3,
        "Amount": 0,
        "Damage": 25,
        "PierceLimit": 1000,
        "Scale": 1,
        "Timeout": 0.5,
        "MovementSpeed": 10,
        "Pin": 1,
    },
    "Revolver": {
        "BlockMovement": 1,
        "Cooldown": 5,
        "Amount": 0,
        "Damage": 20,
        "PierceLimit": 1000,
        "Scale": 1,
        "Timeout": 4,
        "Pin": 1,
        "OrbitRadius": 25,
        "OrbitSpeed": 120,
    },
    "Myst": {
        "Cooldown": 6,
        "Amount": 0,
        "Damage": 2,
        "PierceLimit": 1000,
        "Scale": 1,
        "Timeout": 3,
        "MovementSpeed": 10,
        "MovementAcceleration": -5,
        "PositionRandom1": 40,
        "PositionRandom2": 30,
    },
}

// todo_prod remove * and + stuff (added for testing)