export const Weapons = {
    "_Template": {
        "BlockMovement": 1,
        "Cooldown": 2,
        "Amount": 0,
        "Damage": 0,
        "PierceLimit": 1,
        "AngleOffset": 0,
        "Scale": 1,
        "StaticAngle": -1,
        "Timeout": 4,
        "MovementSpeed": 0,
        "MovementAcceleration": 0,
        "Pin": 0,
        "OrbitRadius": 0,
        "OrbitSpeed": 0,
        "PositionRandom1": 0,
        "PositionRandom2": 0,
    },
    "Axe": {
        "BlockMovement": 1,
        "Cooldown": 1.5,
        "Amount": 1,
        "Damage": 15*10,
        "PierceLimit": 2,
        "AngleOffset": -45,
        "Scale": 0.5,
        "StaticAngle": -1,
        "Timeout": 4,
        "MovementSpeed": 85,
    },
    "Flame": {
        "BlockMovement": 1,
        "Cooldown": 3,
        "Amount": 0,
        "Damage": 25,
        "PierceLimit": 1000,
        "AngleOffset": 45,
        "Scale": 0.5,
        "StaticAngle": -1,
        "Timeout": 0.5,
        "MovementSpeed": 10,
        "Pin": 1,
    },
    "Chainsaw": {
        "BlockMovement": 1,
        "Cooldown": 5,
        "Amount": 0,
        "Damage": 20,
        "PierceLimit": 1000,
        "Scale": 0.5,
        "StaticAngle": -1,
        "Timeout": 4,
        "Pin": 1,
        "OrbitRadius": 25,
        "OrbitSpeed": 120,
    },
    "Spikes": {
        "Cooldown": 6,
        "Amount": 0,
        "Damage": 2,
        "PierceLimit": 1000,
        "Scale": 0.5,
        "StaticAngle": 0,
        "Timeout": 3,
        "PositionRandom1": 40,
        "PositionRandom2": 30,
    },
}

// todo_prod remove * and + stuff (added for testing)